name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      # Build for all platforms - no upload during this phase
      - name: Build for Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          npm ci
          npm run build
          mkdir -p ./artifacts
          npx electron-builder --windows --publish never
          # Move files to artifacts directory
          mkdir -p ./artifacts
          xcopy /E /I /Y dist\* artifacts\
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          npm ci
          npm run build
          npx electron-builder --mac --publish never
          # Move files to artifacts directory
          mkdir -p ./artifacts
          cp -R dist/* artifacts/ || echo "No files to copy"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build for Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          npm ci
          npm run build
          npx electron-builder --linux deb --x64 --publish never
          # Move files to artifacts directory
          mkdir -p ./artifacts
          cp -R dist/* artifacts/ || echo "No files to copy"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Solution 1: Use upload-artifact@v4
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: artifacts/
          if-no-files-found: warn
      
      # Create GitHub release only if triggered by a tag
      - name: Release Electron app - Windows
        if: startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          
      - name: Release Electron app - MacOS
        if: startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v')
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          
      - name: Release Electron app - Linux
        if: startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
