name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v0.0.0'
      release_name:
        description: 'Release name'
        required: false
        default: 'Manual Release'

permissions:
  contents: write
  packages: write
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Build for each platform
      - name: Build app
        run: |
          npm ci
          npm run build
          
      # Build for each platform
      - name: Build and upload - Windows
        if: startsWith(matrix.os, 'windows')
        run: npx electron-builder --windows --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and upload - macOS
        if: startsWith(matrix.os, 'macos')
        run: npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and upload - Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: npx electron-builder --linux deb --x64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Upload artifacts for workflow summary
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/
            release/
          if-no-files-found: warn
          
      # Create release for tag-triggered runs
      - name: Release from tag
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
            release/**/*
          draft: false
          prerelease: false
          
      # Create release for manual runs with specified tag
      - name: Release from manual trigger
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
            release/**/*
          tag_name: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: false
