name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Package Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          npm ci
          npm run build
          # Build only the .deb package for Linux
          npx electron-builder --linux deb --x64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Windows build
      - name: Build Electron app - Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          npm ci
          npm run build
          npx electron-builder --windows --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # macOS build
      - name: Build Electron app - MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          npm ci
          npm run build
          npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload artifacts for all platforms
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.deb
            dist/*.AppImage
            dist/*.snap
            dist/*.yml
          if-no-files-found: ignore
      
      # Create GitHub release only if triggered by a tag
      - name: Release Electron app - Windows
        uses: samuelmeuli/action-electron-builder@v1
        if: startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          
      - name: Release Electron app - MacOS
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        if: startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          
      - name: Release Electron app - Linux
        uses: samuelmeuli/action-electron-builder@v1
        if: startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
