name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Build for each platform
      - name: Build app
        run: |
          npm ci
          npm run build
          
      # Build and upload artifacts for each platform
      - name: Build and upload - Windows
        if: startsWith(matrix.os, 'windows')
        run: npx electron-builder --windows --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and upload - macOS
        if: startsWith(matrix.os, 'macos')
        run: npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and upload - Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: npx electron-builder --linux deb --x64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Upload artifacts directly from where electron-builder puts them
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/
            release/
          if-no-files-found: warn
          
      # Create GitHub release only if triggered by a tag
      - name: Release Electron app - Windows
        if: startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          
      - name: Release Electron app - MacOS
        if: startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/v')
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          
      - name: Release Electron app - Linux
        if: startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
