name: Release

on:
  create:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Package Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          npm ci
          npm run build
          # Build only the .deb package for Linux
          npx electron-builder --linux deb --x64 --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Electron app - Windows
        uses: samuelmeuli/action-electron-builder@v1
        if: startsWith(matrix.os, 'windows')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          
      - name: Release Electron app - MacOS
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        if: startsWith(matrix.os, 'macos')
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Release Electron app - Linux
        uses: samuelmeuli/action-electron-builder@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
